module.exports = {
  TITLE: "Samuel Wong — Hong Kong UI/UX Designer | Desktop of Samuel",
  DESCRIPTION: "I'm Samuel, I'm a Hong Kong based UI/UX Designer. User Interface Design, User Experience Design, Product Design, Design Thinking, Product Development, Brand Design - A personal design portfolio, also journal for designers' side-projects.",
  KEYWORDS: "科技,設計,UI,UX,旅行,城市,香港",
  URL: "https://desktopofsamuel.com",
  PATH_PREFIX: "",
  USERNAME: "@desktopofsamuel",
  EMAIL: "",
  LOCATION: "Hong Kong",
  POSTS_PER_PAGE: 6,
  AUTHOR_NAME: "Samuel W.",
  TWITTER_USERNAME: "@desktopofsamuel",
  COPYRIGHT: "© 版權所有",
  OG_IMAGE: "/opengraph.png",
  LOCALE: "en",
};
